spring:
  application:
    name: file-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/file_microservice_db
    username: postgres
    password: sde9REBKA435k
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

baseUrl: http://localhost:8080

server:
  port: 8088

#spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB