spring:
  application:
    name: browser-frontend
server:
  port: 8085

endpoint:
  service:
    exchange:
      rate: exchangerate-service

# LOGGING
logging:
  level:
    org:
      springframework:
        security: TRACE
        messaging: TRACE
        web:
          socket: TRACE

project:
  path:
    icon: /images/favicon.ico