
# FROM openjdk:23
#
# WORKDIR /app
#
# COPY target/ app.jar
#
# EXPOSE 8082
#
# ENTRYPOINT ["java", "-jar", "app.jar"]

# docker build -t storage-service .
# docker container run -p 8082:8082 storage-service