spring:
  application:
    name: chat-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_microservice_db
    username: postgres
    password: sde9REBKA435k
  jpa:
    hibernate:
      #      ddl-auto: create-drop, update
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8086